### ISSUE TITLE
After creating and deleting a few TODOs there is a strange padding.

### ISSUE THREAD

**Issue by kkd26** [AleksanderMisztal/js-apps#2]
Create a few TODOs, delete them and then create one more TODO. You will see a strange padding.

The deleted TODOs are still there but with class "fall" and opacity 0.

Quick fix: change display to none

**Comment by kkd26** [comment]
If you want to see the animation, then you have to add the animation, not only the final result

transform: translateY(8rem) rotateZ(20deg);
opacity: 0;

Quick fix:
.fall{
    transition: all 1s;
}

after this transition consider removing this TODO items from DOM, not only hide them.

**Comment by AleksanderMisztal** [comment]
Gracias
